// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB57MMGXtNpapzwKpdcOyphrHJwcPHeyIQ',
    appId: '1:1081668884534:web:15da93c23e1d5d2bcee097',
    messagingSenderId: '1081668884534',
    projectId: 'newsapp-c68ba',
    authDomain: 'newsapp-c68ba.firebaseapp.com',
    storageBucket: 'newsapp-c68ba.firebasestorage.app',
    measurementId: 'G-1M99HLYVZZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA15Z_vm02n3t7_ur8FvcX2ZtMiUxGs1kY',
    appId: '1:1081668884534:android:46c19c38678a5963cee097',
    messagingSenderId: '1081668884534',
    projectId: 'newsapp-c68ba',
    storageBucket: 'newsapp-c68ba.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB57MMGXtNpapzwKpdcOyphrHJwcPHeyIQ',
    appId: '1:1081668884534:web:537ff8d84062e643cee097',
    messagingSenderId: '1081668884534',
    projectId: 'newsapp-c68ba',
    authDomain: 'newsapp-c68ba.firebaseapp.com',
    storageBucket: 'newsapp-c68ba.firebasestorage.app',
    measurementId: 'G-X45TF8P18Y',
  );
}
